<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" total="8" passed="4">
  <reporter-output>
    <line>
      <![CDATA[Test yrd]]>
    </line>
  </reporter-output>
  <suite name="Suite1" duration-ms="5140" started-at="2017-06-07T03:34:43Z" finished-at="2017-06-07T03:34:49Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="68" started-at="2017-06-07T03:34:43Z" finished-at="2017-06-07T03:34:43Z">
      <class name="testng.ReporterListenerExample">
        <test-method status="PASS" signature="testAssert1(int)[pri:0, instance:testng.ReporterListenerExample@5dfcfece]" name="testAssert1" duration-ms="23" started-at="2017-06-07T11:34:43Z" data-provider="dataProvider" finished-at="2017-06-07T11:34:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert1 -->
        <test-method status="PASS" signature="testAssert1(int)[pri:0, instance:testng.ReporterListenerExample@5dfcfece]" name="testAssert1" duration-ms="2" started-at="2017-06-07T11:34:43Z" data-provider="dataProvider" finished-at="2017-06-07T11:34:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert1 -->
        <test-method status="PASS" signature="testAssert2()[pri:0, instance:testng.ReporterListenerExample@5dfcfece]" name="testAssert2" duration-ms="2" started-at="2017-06-07T11:34:43Z" finished-at="2017-06-07T11:34:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert2 -->
        <test-method status="SKIP" signature="testAssert3(int)[pri:0, instance:testng.ReporterListenerExample@5dfcfece]" name="testAssert3" duration-ms="0" started-at="2017-06-07T11:34:43Z" finished-at="2017-06-07T11:34:43Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method testAssert3 requires 1 parameters but 0 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method testAssert3 requires 1 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:191)
	at org.testng.internal.Parameters.createParameters(Parameters.java:127)
	at org.testng.internal.Parameters.createParameters(Parameters.java:376)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:451)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert3 -->
      </class> <!-- testng.ReporterListenerExample -->
    </test> <!-- test1 -->
    <test name="test2" duration-ms="17" started-at="2017-06-07T03:34:49Z" finished-at="2017-06-07T03:34:49Z">
      <class name="testng.TestListenerExample">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testng.TestListenerExample@5c7fa833]" name="beforeTest" is-config="true" duration-ms="1" started-at="2017-06-07T11:34:49Z" finished-at="2017-06-07T11:34:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="t1()[pri:0, instance:testng.TestListenerExample@5c7fa833]" name="t1" duration-ms="2" started-at="2017-06-07T11:34:49Z" finished-at="2017-06-07T11:34:49Z">
          <reporter-output>
            <line>
              <![CDATA[Test yrd]]>
            </line>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method status="FAIL" signature="t2()[pri:0, instance:testng.TestListenerExample@5c7fa833]" name="t2" duration-ms="1" started-at="2017-06-07T11:34:49Z" finished-at="2017-06-07T11:34:49Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method TestListenerExample.t2()[pri:0, instance:testng.TestListenerExample@5c7fa833] should have thrown an exception of type class java.lang.RuntimeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method TestListenerExample.t2()[pri:0, instance:testng.TestListenerExample@5c7fa833] should have thrown an exception of type class java.lang.RuntimeException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1381)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:681)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
        <test-method status="SKIP" signature="t3(java.lang.String)[pri:0, instance:testng.TestListenerExample@5c7fa833]" name="t3" duration-ms="0" started-at="2017-06-07T11:34:49Z" finished-at="2017-06-07T11:34:49Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method t3 requires 1 parameters but 0 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method t3 requires 1 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:191)
	at org.testng.internal.Parameters.createParameters(Parameters.java:127)
	at org.testng.internal.Parameters.createParameters(Parameters.java:376)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:451)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t3 -->
        <test-method status="FAIL" signature="t4()[pri:0, instance:testng.TestListenerExample@5c7fa833]" name="t4" duration-ms="1" started-at="2017-06-07T11:34:49Z" finished-at="2017-06-07T11:34:49Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Some other message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Some other message
	at testng.TestListenerExample.t4(TestListenerExample.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.RuntimeException: Some message
	at testng.TestListenerExample.t4(TestListenerExample.java:42)
	... 24 more
Caused by: java.lang.RuntimeException: Some message
	at testng.TestListenerExample.t4(TestListenerExample.java:41)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testng.TestListenerExample@5c7fa833]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-06-07T11:34:54Z" finished-at="2017-06-07T11:34:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testng.TestListenerExample -->
    </test> <!-- test2 -->
  </suite> <!-- Suite1 -->
</testng-results>
